language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="django==1.7"
  - DJANGO="django==1.6.7"
  - DJANGO="django==1.5.10"
  - DJANGO="django==1.4.15"

install:
  - pip install $DJANGO
  - pip install djangorestframework==2.4.2
  - pip install pytest-django==2.6.1
  - pip install flake8==2.2.2
  - pip install oauth2==1.5.211
  - pip install django-oauth-plus==2.2.4
  - pip install django-oauth2-provider
  - export PYTHONPATH=.

script:
  - ./runtests.py

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="django==1.7"
